### ISSUE TITLE
smart init should use batch_size

### ISSUE THREAD

**Issue by thouis** [PLN-team/pyPLNmodels#3]
Hello,

Thanks for a great package.  I'm trying to fit PLN-PCA to single-cell data with ~60,000 cells and ~20,000 genes.  I was happy to see you had added batch_size for fitting.  However, the smart_init code does not work with batch_size, leading to out-of-memory when trying to use the GPU.

**Comment by Bastien-mva** [comment]
Hello, 

I am going to check this, thanks for the issue. 

Bastien

**Comment by Bastien-mva** [comment]
Sorry for the late come back. 

The issue is fixed.

I have been running some tests and it sounds that the mini-batch optimization does not speed up the optimization compared to full-batch optimization. If you do not have GPU, it is not effective at all to use mini-batch optimization. If you do have GPU, it could have memory benefits but I have not test if this is the case. I do switch back and forth parameters on the CPU/GPU when needed but it may not be optimal. 

For the amount of data you have, it may takes a lot of time if you do not have GPU. To give you an idea, for PLN-PCA with rank 5, it takes about 2 hours for 20000 cells and 14000 genes. It is significantly reduced with GPU. An overview of the running time will be available soon. 

I have just tried on my computer that has 24GB RAM on GPU for 60k cells and 20k genes, it does not fit in memory.
